<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/numpy/array_oriented_programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Massivga yo'naltirilgan dasturlash.

### Mantiqiy shart operatorlari.

In [ ]:
import numpy as np

where - funksiyasi.

In [ ]:
arr1 = np.arange(1,11)
arr2 = np.arange(21,31) # bu yerda 2 ta turlicha massiv yaratdik.

In [ ]:
condition = np.array([True,False,False,True,False,False,True,False,True,True])
condition # bu yerda boolen malumot turidan iborat massiv yaratdik kelajakda shart aperatorida ishlatish uchun.

array([ True, False, False,  True, False, False,  True, False,  True,
        True])

In [ ]:
natija = np.where(condition,arr1,arr2) # bu yerda funksiya conditionning har bir elementini o'qiyda agar True bo'lsa arr1 dan mos element oladi agar
                                       #  False bo'lsa arr2 dan oladi va yangi massiv qaytaradi. bu yerda 3 ta massivning ham element soni teng bo'lishi kerak.

In [ ]:
natija

array([ 1, 22, 23,  4, 25, 26,  7, 28,  9, 10])

In [ ]:
arr3 = np.random.randn(5,5)
arr3

array([[ 1.36013135, -1.76152005,  1.96557059,  0.53092184, -2.14507912],
       [ 0.09050233, -1.22131719, -0.87906536,  0.30234334, -1.38704181],
       [-0.31067073,  0.5390943 ,  0.15421585, -0.24412002, -0.75472296],
       [-1.17178282, -0.17949105, -1.08986975, -1.32519956, -0.0753516 ],
       [-0.08287524,  0.69508808,  1.77656547, -0.74210385, -0.08592952]])

In [ ]:
np.where(arr3<0, arr3*(-1), arr3) # bu yerda arr3 massivimizning barcha elementlarini musbat qilib olyapmiz.

array([[1.36013135, 1.76152005, 1.96557059, 0.53092184, 2.14507912],
       [0.09050233, 1.22131719, 0.87906536, 0.30234334, 1.38704181],
       [0.31067073, 0.5390943 , 0.15421585, 0.24412002, 0.75472296],
       [1.17178282, 0.17949105, 1.08986975, 1.32519956, 0.0753516 ],
       [0.08287524, 0.69508808, 1.77656547, 0.74210385, 0.08592952]])

In [ ]:
np.fabs(arr3) # barcha elementlarnining modulini qaytaruvchi funksiya

array([[1.36013135, 1.76152005, 1.96557059, 0.53092184, 2.14507912],
       [0.09050233, 1.22131719, 0.87906536, 0.30234334, 1.38704181],
       [0.31067073, 0.5390943 , 0.15421585, 0.24412002, 0.75472296],
       [1.17178282, 0.17949105, 1.08986975, 1.32519956, 0.0753516 ],
       [0.08287524, 0.69508808, 1.77656547, 0.74210385, 0.08592952]])

In [ ]:
np.where(np.fabs(arr3)<0.1, 0,arr3) # bu yerda elementlarning mpduli 0.1 dan kichik bo'lgan elementlarni 0 ga tenglab yubordik.

array([[ 1.36013135, -1.76152005,  1.96557059,  0.53092184, -2.14507912],
       [ 0.        , -1.22131719, -0.87906536,  0.30234334, -1.38704181],
       [-0.31067073,  0.5390943 ,  0.15421585, -0.24412002, -0.75472296],
       [-1.17178282, -0.17949105, -1.08986975, -1.32519956,  0.        ],
       [ 0.        ,  0.69508808,  1.77656547, -0.74210385,  0.        ]])

In [ ]:
np.where((arr3<0.1)&(arr3>(-0.1)), 0, arr3) # bu yerda xuddi shu ishni fabs funksiyasidan foydalanmasdan amalga oshirdik.

array([[ 1.36013135, -1.76152005,  1.96557059,  0.53092184, -2.14507912],
       [ 0.        , -1.22131719, -0.87906536,  0.30234334, -1.38704181],
       [-0.31067073,  0.5390943 ,  0.15421585, -0.24412002, -0.75472296],
       [-1.17178282, -0.17949105, -1.08986975, -1.32519956,  0.        ],
       [ 0.        ,  0.69508808,  1.77656547, -0.74210385,  0.        ]])

In [ ]:
arr3

array([[ 1.36013135, -1.76152005,  1.96557059,  0.53092184, -2.14507912],
       [ 0.09050233, -1.22131719, -0.87906536,  0.30234334, -1.38704181],
       [-0.31067073,  0.5390943 ,  0.15421585, -0.24412002, -0.75472296],
       [-1.17178282, -0.17949105, -1.08986975, -1.32519956, -0.0753516 ],
       [-0.08287524,  0.69508808,  1.77656547, -0.74210385, -0.08592952]])

In [ ]:
qator, ustun =np.where(arr3>0)

In [ ]:
print(qator)
print(ustun)

[0 0 0 1 1 2 2 4 4]
[0 2 3 0 3 1 2 1 2]


In [ ]:
joylashuv = np.array([qator,ustun])
joylashuv

array([[0, 0, 0, 1, 1, 2, 2, 4, 4],
       [0, 2, 3, 0, 3, 1, 2, 1, 2]])

In [ ]:
aniqjoylashuv = joylashuv.T # bu yerda arr3 massivimizdagi 0 dan katta bo'lgan elementlarimizning indexlarini ajratib aniqjoylashuv nomli massivimizga saqladik.
print(aniqjoylashuv)

[[0 0]
 [0 2]
 [0 3]
 [1 0]
 [1 3]
 [2 1]
 [2 2]
 [4 1]
 [4 2]]


In [ ]:
musbat_sonlar = np.array([])
for i in aniqjoylashuv: # bu yerda aniqjoylashuv massivimizdagi elementlardan foydalanib arr3dagi musbat soblarni ekranga chiqardik.
  a = i[0]
  b = i[1]
  musbat_sonlar = np.append(musbat_sonlar, arr3[a,b])  # qo'shimchasiga barcha musbat sonlarni alohida massivga yuklab oldik.
  print(arr3[a,b])

1.3601313508768094
1.9655705898191507
0.5309218431440905
0.09050233121598239
0.30234334095782306
0.5390942954732311
0.154215845500683
0.6950880793874631
1.7765654668048327


In [ ]:
print(musbat_sonlar)

[1.36013135 1.96557059 0.53092184 0.09050233 0.30234334 0.5390943
 0.15421585 0.69508808 1.77656547]


## Arifmetik amallar.

ko'paytirish, bo'lish, ayirish, qo'shish va boshqa amallar.

In [ ]:
arr4 = np.array([2,6,3,9,3,0]).reshape(2,3)
arr5 = np.array([4,6,5,8,9,1]).reshape(2,3)

In [ ]:
arr4

array([[2, 6, 3],
       [9, 3, 0]])

In [ ]:
arr5

array([[4, 6, 5],
       [8, 9, 1]])

In [ ]:
arr4*arr5 # ko'paytirish amali massivlarning mos elementlarini biri biriga ko'paytiradi.

array([[ 8, 36, 15],
       [72, 27,  0]])

In [ ]:
arr4/arr5 # bo'lganda ham massivlarning mos elementlarini bir biriga bo'ladi.

array([[0.5       , 1.        , 0.6       ],
       [1.125     , 0.33333333, 0.        ]])

In [ ]:
arr4+arr5 # massivlarni bir biriga qo'shdik.

array([[ 6, 12,  8],
       [17, 12,  1]])

In [ ]:
arr5-arr4 # massivlarni bir biridan ayirdik.

array([[ 2,  0,  2],
       [-1,  6,  1]])

In [ ]:
arr4**2 # massivning kvadratini hisopladik.

array([[ 4, 36,  9],
       [81,  9,  0]])

In [ ]:
arr5**0.5 # massivning ildizini hisopladik.

array([[2.        , 2.44948974, 2.23606798],
       [2.82842712, 3.        , 1.        ]])

## matematik va statistik usullardan foydalanish.

In [ ]:
arr6 = np.random.randn(3,5)
arr6

array([[-0.42145855, -1.67459153, -0.16775706,  0.23629074,  0.15736538],
       [-0.65247171, -0.04655784, -0.00627003,  1.67513498, -2.49952632],
       [ 0.99017394,  0.78361114, -1.12068226,  0.33597519, -0.27891985]])

In [ ]:
arr6.sum() # bu method massivning barcha elementlari yig'indisini qaytaradi.

np.float64(-2.6896837784703913)

In [ ]:
np.sum(arr6)

np.float64(-2.6896837784703913)

In [ ]:
arr6.sum(axis=1) # bu yerda qatorlar bo'yicha sum methodini qo'lladik.

array([-1.87015102, -1.52969092,  0.71015816])

In [ ]:
arr6.mean() # bu method massiv elementlarining o'rtacha arifmetik qiymatini qaytaradi.

np.float64(-0.17931225189802608)

In [ ]:
np.mean(arr6)

np.float64(-0.17931225189802608)

In [ ]:
arr7 = np.array([1,2,4,6,9])

In [ ]:
arr7.cumsum() # bu method har bir massiv elementi joyiga o'zidan avvalgi barcha va o'zining yig'indisini hisoblab joylaydi.

array([ 1,  3,  7, 13, 22])

In [ ]:
arr7 = np.append(arr7, 5).reshape(2,3)
arr7


array([[1, 2, 4],
       [6, 9, 5]])

In [ ]:
arr7.cumsum(axis=1)

array([[ 1,  3,  7],
       [ 6, 15, 20]])

In [ ]:
arr7.cumsum(axis=0)

array([[ 1,  2,  4],
       [ 7, 11,  9]])

In [ ]:
arr7.min(axis = 1) # bu yerda qatorlar bo'yicha eng kichik qiymatni aniqladik.

array([1, 5])

In [ ]:
arr7.cumprod() # yig'ilib boradigan ko'paytman.

array([   1,    2,    8,   48,  432, 2160])

## Tartiblash (sorting)

In [ ]:
arr8 = np.random.randint(1,10, size = 8)
arr8

array([7, 8, 6, 8, 3, 6, 1, 5])

In [ ]:
np.sort(arr8) # sort methodi yordamida tartibladik.

array([1, 3, 5, 6, 6, 7, 8, 8])

In [ ]:
-np.sort(-arr8) # bu yerda massivni teskari tartibda tartibladik.

array([8, 8, 7, 6, 6, 5, 3, 1])

In [ ]:
arr8 = arr8.reshape(2,4)
arr8

array([[7, 8, 6, 8],
       [3, 6, 1, 5]])

In [ ]:
np.sort(arr8, axis=0) # ustun bo'yicha tartibladik.

array([[3, 6, 1, 5],
       [7, 8, 6, 8]])

In [ ]:
np.sort(arr8, axis = 1) # ustun bo'yicha tartibladik.

array([[6, 7, 8, 8],
       [1, 3, 5, 6]])

## unique, isin va setdiff1d fumksiyalari haqida.

In [ ]:
arrstr1 = np.array(['anvar','olim','rustam','ilhom','anvar','sardor','ilhom'])
arrstr1

array(['anvar', 'olim', 'rustam', 'ilhom', 'anvar', 'sardor', 'ilhom'],
      dtype='<U6')

In [ ]:
np.unique(arrstr1) # bu funksiya massivdagi takrorlangan elementlarning faqat 1 tasini qoldirib qolganlarini olib tashlaydi.

array(['anvar', 'ilhom', 'olim', 'rustam', 'sardor'], dtype='<U6')

In [ ]:
arr9 = np.array([1,3,9,4,23,65,12])
arr10 = np.array([3,23,12])
arr9

array([ 1,  3,  9,  4, 23, 65, 12])

In [ ]:
arr10

array([ 3, 23, 12])

In [ ]:
np.isin(arr9,arr10) # mu funksiya 2-massiv elementlarining 1-massivda mavjudligini tekshiradi va mavjud
                    # elementlarning o'rniga True qolganlarining o'rniga esa False qo'yib qaytaradi.

array([False,  True, False, False,  True, False,  True])

In [ ]:
np.setdiff1d(arr9,arr10) # bu funksiya 1-massivning 2-massivda mavjud bo'lmagan elementlarini qaytaradi.

array([ 1,  4,  9, 65])