<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/numpy/numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# universal funksiyalar.

Unary funksiyalar ( 1 ta argument qabul qiluvchi funksiyalar.)

sqrt , square , exp , log , modf , sign , isnan funksiyalari bilan tanishamiz.

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr1) # bu funksiya massivning har bir elementini kv ildizini qaytaradi.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.square(arr1) # square() funksiyasi massiv elementlarining kvadratini qaytaradi.

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.exp(arr1) # bu funksiya har bir elementning exponentini qaytaradi.

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.log(np.exp(arr1)) # bu funksiya e darajali logorifmda har bir element qiymatini qaytaradi.

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.log2(4)

np.float64(2.0)

In [ ]:
arr2 = np.random.randn(10)
arr2

array([ 0.41179186, -0.86205449,  1.09845811, -0.44802879, -2.0927974 ,
        0.21951836, -0.40150824,  0.71836656, -0.27921975, -0.55996565])

In [ ]:
qoldiq_m , butun_m = np.modf(arr2) # bu funksiya har bir elementning butun va qoldiq qismlarini alohida massivlarga joylaydi.

In [ ]:
print(qoldiq_m)
print(butun_m)

[ 0.41179186 -0.86205449  0.09845811 -0.44802879 -0.0927974   0.21951836
 -0.40150824  0.71836656 -0.27921975 -0.55996565]
[ 0. -0.  1. -0. -2.  0. -0.  0. -0. -0.]


In [ ]:
np.modf(arr2)

(array([ 0.41179186, -0.86205449,  0.09845811, -0.44802879, -0.0927974 ,
         0.21951836, -0.40150824,  0.71836656, -0.27921975, -0.55996565]),
 array([ 0., -0.,  1., -0., -2.,  0., -0.,  0., -0., -0.]))

In [ ]:
np.sign(arr2)

array([ 1., -1.,  1., -1., -1.,  1., -1.,  1., -1., -1.])

In [ ]:
arr3 = np.array([-12,34,1,5,-7,54,-234])

In [ ]:
np.sign(arr3) # bu funksiya massiv elementlarining ishoralarini qaytaradi.

array([-1,  1,  1,  1, -1,  1, -1])

In [ ]:
arr3 = np.float64(arr3)
arr3[4:] = np.nan

In [ ]:
np.isnan(arr3) # bu funksiya massivdagi nan qiymatlarni aniqlaydi va ular o'rniga true qolganlariga esa false qiymat yuklab massiv qaytaradi.

array([False, False, False, False,  True,  True,  True])

abs, fabs, ceil, floor va rint funksiyalari.

In [ ]:
np.abs([3+4j])     # [5.] bu funksiya massiv ichidagi har bir elementning modulini qaytaradi. istalgan turdagi sonlar uchun: int, float, complex

array([5.])

In [ ]:
np.fabs([-12,4]) # faqat real sonlar bilan ishlaydi farqi shunda va faqat float qiymat qaytaradi.

array([12.,  4.])

In [ ]:
np.ceil([-1.2, -2.8, 1.1, 3.7]) # bu funksiya sonning o'zini yoki o'zidan katta bo'lgan butun sonni qaytaradi.

array([-1., -2.,  2.,  4.])

In [ ]:
np.floor([-1.2, -2.8, 1.1, 3.7]) # bu funksiya sonning o'zini yoki o'zidan kichik bo'lgan butun sonni qaytaradi.

array([-2., -3.,  1.,  3.])

In [ ]:
np.rint([-1.2, -2.8, 1.1, 3.7]) # sonning o'zini yoki o'ziga eng yaqin bo'lgan butun sonni qaytaradi.

array([-1., -3.,  1.,  4.])

## Binary funksiyalar-ikkita argument qabul qiluvchi funksiyalar.

add, multiply, maximum  funksiyalarini ko'rib chiqamiz.

In [ ]:
arr6 = np.random.randn(7)
arr5 = np.random.randn(7)

In [ ]:
arr6

array([-0.03630494, -1.70328352, -0.11204497,  0.80180197, -1.31428217,
       -1.53888288, -0.47325416])

In [ ]:
arr5

array([-0.4748206 ,  1.39019404, -1.6637033 ,  1.04879339, -0.81252686,
       -0.45936178,  0.23997192])

In [ ]:
np.add(arr5,arr6) # add funksiyasi massivlarning mos elementlarini qo'shib bitta umumiy massiv qaytaradi.

array([-0.51112553, -0.31308947, -1.77574826,  1.85059536, -2.12680903,
       -1.99824466, -0.23328224])

In [ ]:
np.multiply(arr5,arr6) # multiply funksiyasi massivlarning mos elementlarini bir biriga ko'paytirib qaytaradi.

array([ 0.01723833, -2.3678946 ,  0.18640958,  0.84092461,  1.06788957,
        0.70690398, -0.11356771])

In [ ]:
np.maximum(arr5,arr6) # maximum funksiyasi massivlarning mos elementlarini solishtirib ularning kattasini qaytaradi.

array([-0.03630494,  1.39019404, -0.11204497,  1.04879339, -0.81252686,
       -0.45936178,  0.23997192])

subtrack, power, mod, copysign funksiyalari haqida gaplashamiz.

In [ ]:
arr7 = np.array([3,4,5])
arr8 = np.array([7,9,12])

In [ ]:
np.subtract(arr8,arr7) # birinchi massiv elementlaridan ikkinchi massiv elementlarini ayiradi.

array([4, 5, 7])

In [ ]:
np.power(arr8,arr7)

array([   343,   6561, 248832])

In [ ]:
np.power([3,5,4],3) # bu funksiya birinchi elementning ikkinchi elementinchi darajasini hisoblaydi.

array([ 27, 125,  64])

In [ ]:
np.mod(arr8,arr7)

array([1, 1, 2])

In [ ]:
np.mod(17,6) # bu funksiya birinchi elementni ikkinchi elementga bo'ladi va qoldiqni qaytaradi.

np.int64(5)

In [ ]:
arr9 = np.array([-3,2,-11])

In [ ]:
arr8

array([ 7,  9, 12])

In [ ]:
arr9

array([ -3,   2, -11])

In [ ]:
np.copysign(arr8,arr9) # copysign funksiyasi ikkinchi element ishorasini birinchi elementga be

array([ -7.,   9., -12.])