<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/numpy/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasi.

numpy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

numpy massivlari bilan ishlash.

In [ ]:
data1 = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr1 = np.array(data1)
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr1.ndim # massivimizning o'lchamini ko'rsatadi.

3

shape va size metodlari

In [ ]:
arr1.shape # massivimizning qator va ustunlari sonini ko'rsatadi (q,u)

(2, 2, 3)

In [ ]:
arr1.size # massivimizning umumiy elementlar sonini ko'rsatadi.

12

zeros va ones funksiyalari.


In [ ]:
arr2 = np.zeros(shape = (2,3)) # malum bir shakldagi barcha qiymatlari 0 bo'lgan massive yaratib beradi.
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr3 = np.ones(shape = (3,3)) #malum bir shakldagi barcha qiymatlari 1 bo'lgan massive yaratib beradi.
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

arang() funksiyasi.

In [ ]:
arr4 = np.arange(5,30,3) # pythondagi range funksiyasi bilan bir xil.
arr4

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

random funksiyasi (rand, randint, randn)

In [ ]:
arr5 = np.random.rand(3,4) # (3,4) o'lchamli qiymatlari 0 va 1 oralig'idagi massive yaratadi.
arr5

array([[0.61664411, 0.9427815 , 0.74891748, 0.9717331 ],
       [0.48693041, 0.22993123, 0.21373   , 0.98978098],
       [0.11992144, 0.57922535, 0.69386356, 0.1629274 ]])

In [ ]:
arr6 = np.random.randint(7,size = (3,3)) # qiymatlari 0 dan 7 gacha bo'lgan (3,3) o'lchamli massive yaratadi.
arr6

array([[2, 4, 6],
       [5, 4, 6],
       [3, 3, 5]])

In [ ]:
arr7 = np.random.randn(2,4)
arr7

array([[-1.18197086,  1.27586216,  0.00289334,  0.13252266],
       [ 1.58423674,  0.48635755,  0.4807331 , -0.33967365]])

In [ ]:
arr8 = np.ones_like(arr6) # arr6 ning shaklidagi faqat qiymatlari 1 ga teng massive qaytaradi.
arr8

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr9 = np.full_like(arr6,fill_value="falonchi",dtype=str)
arr9

array([['f', 'f', 'f'],
       ['f', 'f', 'f'],
       ['f', 'f', 'f']], dtype='<U1')

In [ ]:
arr10 = np.full_like(arr9,fill_value="salom")
arr10

array([['s', 's', 's'],
       ['s', 's', 's'],
       ['s', 's', 's']], dtype='<U1')

In [ ]:
arr11 = np.full((2,3),fill_value="S", dtype=str)
arr11

array([['S', 'S', 'S'],
       ['S', 'S', 'S']], dtype='<U1')

amaliyot. massive yaratish bo'yicha vazifalar

In [ ]:
def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
  my_arr1 = np.random.randint(9,size = (n))
  return my_arr1

In [ ]:
arr12 = one_dim(10)
arr12

array([6, 3, 3, 1, 5, 2, 0, 7, 6, 1])

In [ ]:
arr13 = np.random.randint(9,size = (3))
arr13

array([7, 6, 1])