<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/numpy/numpy_array_datatypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy kutubxonasida malumot turlari bilan ishlash. malumot turlarini aniqlash, kiritish, o'zgartirish va boshqa amallar.

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,6], dtype=np.int32)
arr1

array([1, 2, 3, 6], dtype=int32)

In [ ]:
arr2 = np.array([5,2,7,9], dtype=np.float32)
arr2

array([5., 2., 7., 9.], dtype=float32)

In [ ]:
arr1.dtype

dtype('int32')

In [ ]:
arr2.dtype

dtype('float32')

bir turdagi malumot turidan boshqasiga o'girish.

In [ ]:
arr3 = np.array([23,2345,2345,8765]) # bu yerda numpy butun sonlarga avtomatik int64 malumot turini tanlaydi.
arr3.dtype

dtype('int64')

astype metodi.

In [ ]:
arr_float = arr3.astype(np.float32)
arr_float.dtype

dtype('float32')

In [ ]:
my_float_data = np.array([7.5,4.8,1.1,4,7]) # float64 malumot turi.
my_float_data.dtype

dtype('float64')

In [ ]:
my_float_data

array([7.5, 4.8, 1.1, 4. , 7. ])

In [ ]:
my_int_data = my_float_data.astype(np.int32) # bu yerda numpyda float dan int ga o'tayotganda sonning faqat butun qismlari o'tadi.
my_int_data

array([7, 4, 1, 4, 7], dtype=int32)

In [ ]:
my_int_data.dtype

dtype('int32')

## massivlarda indexlar bilan ishlash.

In [ ]:
arr4 = np.arange(5,30,2,dtype=np.int16)
arr4

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29], dtype=int16)

In [ ]:
arr4[3] # index orqali 1 ta malumot olganimizda malumot turini ham ko'rishimiz mumkin.

np.int16(11)

In [ ]:
arr4[3:7] # elementlarni indexlari orqali kesib olish.

array([11, 13, 15, 17], dtype=int16)

In [ ]:
sliced = arr4[5:8]
sliced

array([15, 17, 19], dtype=int16)

In [ ]:
sliced[1]=1211 # bu yerda index orqali massivning malum elementini o'zgartirdik.
sliced

array([  15, 1211,   19], dtype=int16)

In [ ]:
arr4 # bu yerda ikkala o'zgaruvchi ham bir manbaga bog'langanligi sababli ikkala massivda ham o'zgarish yuz berdi.

array([   5,    7,    9,   11,   13,   15, 1211,   19,   21,   23,   25,
         27,   29], dtype=int16)

copy() metodidan foydalanish.

In [ ]:
sliced_arr4 = arr4[0:4].copy()
sliced_arr4

array([ 5,  7,  9, 11], dtype=int16)

In [ ]:
sliced_arr4[:] = 0
sliced_arr4

array([0, 0, 0, 0], dtype=int16)

In [ ]:
arr4 # copy metodidan foydalanganligimiz sababli ikki massiv alohida malumotga bog'landi natijada biridagi o'zgarish ikkinchisiga tasir qilmadi.

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29], dtype=int16)

 2 o'lchamli massivlarda indexlar orqali kesib olish.

In [ ]:
arr5 =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr5[1,2]

np.int64(6)

In [ ]:
arr5[0,2]

np.int64(3)

In [ ]:
arr5[0,2:]

array([3])

In [ ]:
arr5[1,1:]

array([5, 6])

In [ ]:
arr5[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
arr5[1:2,:3]

array([[4, 5, 6]])

In [ ]:
arr5[:2,1:]

array([[2, 3],
       [5, 6]])

3 o'lchamli massivlar bilan ishlash.

In [ ]:
arr6 = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])



In [ ]:
arr6[1][1:,1:]

array([[13, 14],
       [16, 17]])

boolen bilan indexlash.

In [ ]:
ismlar = np.array(['sardor','elyor','mirkomil','sardor','islom'])

In [ ]:
arr7 = np.random.randint(9,size=(5,4))
arr7

array([[1, 4, 1, 8],
       [0, 3, 6, 0],
       [2, 3, 7, 3],
       [3, 4, 5, 2],
       [0, 5, 4, 1]])

In [ ]:
ismlar == 'sardor' # bu yerda kiritgan malumot ismlar massivining qaysi elementi bilan bir
# xil bo'lsa shu element indexga True qolgan indexlarga esa False qiymat kiritib qaytaradi.

array([ True, False, False,  True, False])

In [ ]:
arr7[ismlar=='sardor'] # bu yerda boolen dan foydalanib arr7 dagi malumotlarni chaqiryapmiz.

array([[1, 4, 1, 8],
       [3, 4, 5, 2]])

In [ ]:
arr7[ismlar!='sardor']

array([[0, 3, 6, 0],
       [2, 3, 7, 3],
       [0, 5, 4, 1]])

In [ ]:
arr7[~(ismlar=="sardor")]

array([[0, 3, 6, 0],
       [2, 3, 7, 3],
       [0, 5, 4, 1]])

In [ ]:
arr7[ismlar=='sardor']

array([[1, 4, 1, 8],
       [3, 4, 5, 2]])

In [ ]:
arr7[ismlar=='sardor'][:,1:3]

array([[4, 1],
       [4, 5]])

In [ ]:
arr7[ismlar=='sardor',2:3]

array([[1],
       [5]])

In [ ]:
arr7[(ismlar=="elyor") | (ismlar=='islom')]  # (|) or aperatori. bir vaqtda ikki elementga tegishli malumotlarni chiqaryapmiz.

array([[0, 3, 6, 0],
       [0, 5, 4, 1]])

In [ ]:
arr7

array([[1, 4, 1, 8],
       [0, 3, 6, 0],
       [2, 3, 7, 3],
       [3, 4, 5, 2],
       [0, 5, 4, 1]])

In [ ]:
arr7[arr7<4]=0 # 4 dan kichik barcha elementlarni 0 ga tengladik.
arr7

array([[0, 4, 0, 8],
       [0, 0, 6, 0],
       [0, 0, 7, 0],
       [0, 4, 5, 0],
       [0, 5, 4, 0]])

reshape funksiyasi.

In [ ]:
arr7 = np.full((1,9),1)
arr7

array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
re_arr7 = arr7.reshape((3,3))# bu yerda arr7 massivining shaklini o'zgartirdik.
re_arr7

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr8 = np.reshape(np.arange(9),(3,3)) # bu yerda reshape funksiyasi yordamida o'zimiz hoxlagan shakldagi massive yaratdik.
arr8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr9 = np.reshape(arr8,(1,9))
arr9

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

Transpose va swapping axes metodlari.

In [ ]:
arr10 = np.arange(9).reshape(3,3)
arr10

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr10.T # bu yerda qatorlarni ustunlarga ustunlarni esa qatorlarga almashtirdik.

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
arr10.swapaxes(1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
arr10.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

dot metodi. massivlarni bir biriga ko'paytirishda ishlatiladi.

In [ ]:
np.dot(arr10,arr10.T)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])