<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/numpy/numpy_practice_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
print(np.version.version)
print(np.show_config)

2.0.2
<function show at 0x7848367c2e80>


#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr2 = np.zeros(9)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [ ]:
arr2 = np.zeros(12)
arr2[5] = 1
arr2

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr3 = np.arange(20,60)
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [ ]:
arr4 = arr1[::-1]
arr4

array([5, 4, 3, 2, 1])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr5 = np.arange(12,21).reshape(3,3)
arr5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
print(np.nonzero([3,7,0,0,9,0]))

(array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr6 = np.random.random(size=(2,2,2))

arr7 = np.random.rand(2,2,2)
arr7

array([[[0.21975534, 0.45265877],
        [0.01011887, 0.23669407]],

       [[0.32442743, 0.33284645],
        [0.59526192, 0.64062312]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [ ]:
arr8 = np.random.randint(10,size=(9,9))
print(f"maximum element: {arr8.max()}")
print(f"minimum element: {arr8.min()}")

maximum element: 9
minimum element: 0


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
arr9 =np.array([], dtype=object)
arr9 = np.append(arr9,0 * np.nan)
arr9 = np.append(arr9,np.nan == np.nan)
arr9 = np.append(arr9,np.inf > np.nan)
arr9 = np.append(arr9,np.nan - np.nan)
arr9 = np.append(arr9,np.nan in set([np.nan]))
arr9 = np.append(arr9,0.7 == 7 * 0.1)
arr9

array([nan, False, False, nan, True, False], dtype=object)

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr10 = np.random.randint(10,size=(6,3))
arr11 = np.random.randint(10,size=(3,4))
arr12 = np.dot(arr10,arr11)
arr12


array([[25, 44, 24, 48],
       [25, 52, 42, 49],
       [46, 76, 60, 76],
       [55, 64, 54, 69],
       [42, 48, 36, 54],
       [26, 40, 24, 44]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10
[[3 1 7]
 [4 3 1]
 [4 6 4]
 [0 9 5]
 [0 6 6]
 [2 2 6]]


array([11,  8, 14, 14, 12, 10])

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1,2])
b = np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_2884/3227561482.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
/tmp/ipykernel_2884/3227561482.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
/tmp/ipykernel_2884/3227561482.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [ ]:
arr13 = np.array([1,3,5,7,9,4,6])
arr14 = np.array([2,4,8,0,5])
print(np.intersect1d(arr14,arr13))

[4 5]


#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` % (Sonning kasr qismi - qoldiq), np.floor, astype, np.trunc

In [ ]:
arr15 = np.random.rand(10)*10
print(arr15//1)
print(np.floor(arr15))
print(arr15-arr15%1)
print(arr15.astype(np.int16))
print(np.trunc(arr15))

[9. 9. 8. 4. 9. 7. 0. 4. 8. 9.]
[9. 9. 8. 4. 9. 7. 0. 4. 8. 9.]
[9. 9. 8. 4. 9. 7. 0. 4. 8. 9.]
[9 9 8 4 9 7 0 4 8 9]
[9. 9. 8. 4. 9. 7. 0. 4. 8. 9.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [ ]:
arr17 = np.array([])
for i in range(3):
  arr17 = np.append(arr17,np.arange(3))
arr17 = arr17.reshape(3,3)
print(arr17)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
arr18 = np.random.randint(10, size = 10)
print(np.sort(arr18))

[0 1 2 4 6 6 7 7 8 9]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [ ]:
arr19 = np.array([1,4,6,3])
arr20 = np.array([1,4,6,3])
print(np.allclose(arr19,arr20))
print(np.array_equal(arr19,arr20))
print(np.equal(arr19,arr20))

True
True
[ True  True  True  True]


#### 23. 5 dan 15 gacha bo'lgan sonlardan iborat massiv yarating. Massivdagi 10 dan katta elementlarni ajratib oling va ularning yig‘indisini hisoblang.


`💡Ishora` sum()

In [ ]:
arr21 = np.arange(5,16)
print(np.sum(arr21,where=arr21>10))

65


#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [ ]:
arr22 = np.array([2,7,4,9,2,4])
arr22[np.argmax(arr22)]=0
arr22


array([2, 7, 4, 0, 2, 4])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
print(f"kecha - {np.datetime64('now', "D")+np.timedelta64(-1,"D")}")
print(f"bugun - {np.datetime64('now', "D")}")
print(f"ertaga - {np.datetime64('now', "D")+np.timedelta64(1,"D")}")

kecha - 2026-04-23
bugun - 2026-04-24
ertaga - 2026-04-25


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
print(np.arange(np.datetime64('2016-01',"D"),np.datetime64('2016-02','D')))

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 2.6, 7.9, 9.8, 4.2 elementlardan tashkil topgan arr yarating va uni arr1 deb nomlang. Keyin massivdagi har bir sonning butun qismini oling va yangi massiv - arr2 ni hosil qiling.


`💡Ishora` astype(int)

In [ ]:
arr23 = np.array([2.6,7.9,9.8,4.2])
arr24 = np.array(np.floor(arr23))
arr24

array([2., 7., 9., 4.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
arr25 = np.array([1,2,3,4,5])
print(np.sum(arr25))
print(np.add.reduce(arr25))

15
15


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
arr26 = np.array([1,2,3,4,5])
arr27= np.zeros(len(arr26)*4)
arr27[::4] = arr26
arr27


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [ ]:
arr28 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print(np.lib.stride_tricks.as_strided(arr28,shape = (11,4),strides=(arr28.strides[0], arr28.strides[0])))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
arr29 = np.array([2,5,3,7,3,6,3,7,8,4,2])
common = np.bincount(arr29)
common
print(f"eng ko'p takrorlangan son: {np.argmax(common)}")

eng ko'p takrorlangan son: 3


#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`